### ISSUE TITLE
App frozen or very slow after creating new repository

### ISSUE THREAD

**Issue by stoneddesigner** [kactus-io/kactus#70] opened 2017-11-18 21:19 UTC
Love the idea of this app and the fact it's open source. It's what Abstract should be (or at least it's 'community edition').

### Description

Created new repo through Kactus, and Kactus seemingly froze during import. After waiting 10-15 mins with the Kactus open and 'loading', Kactus started working, but immediately became slow and quickly unresponsive.

My repository is ~930 megabytes (nearly a gig), so I understand why the app probably took some time to load in the beginning, and even why it's struggling to move around such a large project. But at the same time, this is a fairly new project, and much more to grow -- so it's sad to see I can't utilize the project at this scale.

### Version

**Kactus version:** 0.3.0

iMac (21.5-inch, Mid 2011)
2.5 GHz Intel Core i5
12GB 1333 MHz DDR3
AMD Radeon HD 6750M 512M

**OS version:** macOS Sierra 10.12.1

### Steps to Reproduce

1. Downloaded app.
2. Opened app.
3. Signed into Github
4. Dragged in folder into app
5. App prompted "No repository exists. create new repository?"
6. Created new repository. Git files exist in folder.
7. App loads up repo, loads Sketch files. Here is where the app freezes, underneath the 0 changed files section, in the big white area, I see an infinite loading screen (pictured here: https://imgur.com/a/IpZS2)
8. App finally loads, any buttons I pressed activate on a massive delay (like the Open Repo Folder button).
9. I press History tab, then press the Changes tab (and any other button) and app freezes indefinitely.

Restarting the app allows me to click on sketch files and see the new buttons on the right (open sketch file, etc), but after one click or so it freezes. And if I switch to the History tab and try to switch back (like step 9), it freezes again.

**Expected behavior:** Import repo. Start using the app!

**Actual behavior:** App freezes.

**Reproduces how often:** Every time. 100%

### Logs

2017-11-18T20:36:02.827Z - error: [main] Failed to symlink the kactus sketch plugin null
2017-11-18T20:36:06.636Z - info: [ui] [AppStore] loading 0 repositories from store
2017-11-18T20:36:07.084Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:07.087Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:07.334Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:07.525Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:07.716Z - info: [ui] launching: 0.3.0 (Mac OS 10.12.1)
2017-11-18T20:36:07.719Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:08.116Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:09.314Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.712s)
2017-11-18T20:36:11.320Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
2017-11-18T20:36:11.338Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2017-11-18T20:36:19.479Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2017-11-18T20:36:20.838Z - info: [ui] [AppStore] adding account stoneddesigner (Oscar D) to store
2017-11-18T20:36:20.846Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2017-11-18T20:36:20.988Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:21.302Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-11-18T20:36:29.086Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2017-11-18T20:51:28.639Z - info: [ui] [AppStore] adding repository at /Volumes/WEEDPORNDAILY/Kushy/Sketch/Kushy V2 to store
2017-11-18T20:51:41.829Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 10.460s)
2017-11-18T20:51:45.449Z - info: [ui] Executing createCommit: git commit -F - (took 3.620s)
2017-11-18T20:51:49.490Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.687s)
2017-11-18T20:51:49.498Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 1.706s)
2017-11-18T20:51:50.038Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.210s)
2017-11-18T20:54:08.703Z - info: [ui] [AppStore] loading 1 repositories from store
2017-11-18T20:54:08.706Z - info: [ui] [AppStore] found account: stoneddesigner (Oscar D)
2017-11-18T20:54:10.838Z - info: [ui] Opt in reported.
2017-11-18T20:54:21.970Z - info: [ui] launching: 0.3.0 (Mac OS 10.12.1)
2017-11-18T20:54:22.756Z - info: [ui] Stats reported.
2017-11-18T20:54:26.307Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 13.400s)
2017-11-18T21:00:20.972Z - info: [ui] Executing getRemotes: git remote -v (took 347.150s)
2017-11-18T21:00:38.367Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 364.530s)
2017-11-18T21:00:38.368Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 364.560s)
2017-11-18T21:00:39.570Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 3.279s)
2017-11-18T21:00:39.570Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 3.289s)
2017-11-18T21:00:39.570Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 4.961s)
2017-11-18T21:00:39.571Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 4.972s)
2017-11-18T21:00:39.571Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 6.635s)
2017-11-18T21:00:39.571Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 6.647s)
2017-11-18T21:00:39.571Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 8.325s)
2017-11-18T21:00:39.572Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 8.336s)
2017-11-18T21:00:39.572Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 10.000s)
2017-11-18T21:00:39.572Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 10.009s)
2017-11-18T21:00:39.573Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 11.692s)
2017-11-18T21:00:39.573Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 11.704s)
2017-11-18T21:00:39.573Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 13.359s)
2017-11-18T21:00:39.573Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 13.367s)
2017-11-18T21:00:39.574Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 15.048s)
2017-11-18T21:00:39.574Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 15.057s)
2017-11-18T21:00:39.574Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 16.762s)
2017-11-18T21:00:39.575Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 16.774s)
2017-11-18T21:00:40.164Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 17.332s)
2017-11-18T21:00:44.128Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 9.511s)
2017-11-18T21:00:47.203Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 14.258s)
2017-11-18T21:00:50.311Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 19.054s)
2017-11-18T21:00:54.970Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 25.390s)
2017-11-18T21:00:58.999Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 31.108s)
2017-11-18T21:01:02.179Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 35.959s)
2017-11-18T21:01:06.319Z - info: [ui] Executing getRemotes: git remote -v (took 4.157s)
2017-11-18T21:01:06.320Z - info: [ui] Executing getRemotes: git remote -v (took 7.338s)
2017-11-18T21:01:06.320Z - info: [ui] Executing getRemotes: git remote -v (took 11.371s)
2017-11-18T21:01:06.320Z - info: [ui] Executing getRemotes: git remote -v (took 16.028s)
2017-11-18T21:01:06.321Z - info: [ui] Executing getRemotes: git remote -v (took 19.136s)
2017-11-18T21:01:06.321Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 23.075s)
2017-11-18T21:01:06.322Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 41.790s)
2017-11-18T21:01:12.436Z - info: [ui] Executing getRemotes: git remote -v (took 2.964s)
2017-11-18T21:01:12.436Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 6.951s)
2017-11-18T21:01:12.437Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 10.267s)
2017-11-18T21:01:12.438Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 10.287s)
2017-11-18T21:01:12.438Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 13.448s)
2017-11-18T21:01:12.438Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 13.469s)
2017-11-18T21:01:12.439Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 17.480s)
2017-11-18T21:01:12.439Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 17.504s)
2017-11-18T21:01:12.439Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 22.138s)
2017-11-18T21:01:12.440Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 22.158s)
2017-11-18T21:01:12.440Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 25.247s)
2017-11-18T21:01:12.440Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 25.269s)
2017-11-18T21:01:12.441Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 29.172s)
2017-11-18T21:01:12.645Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 3.163s)
2017-11-18T21:01:12.646Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 3.186s)
2017-11-18T21:01:12.646Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 7.141s)
2017-11-18T21:01:12.746Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 36.448s)
2017-11-18T21:01:17.426Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 5.430s)
2017-11-18T21:01:33.135Z - info: [ui] Executing getRemotes: git remote -v (took 5.426s)
2017-11-18T21:01:35.860Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.822s)
2017-11-18T21:01:35.861Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 2.833s)
2017-11-18T21:01:35.861Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 5.624s)
2017-11-18T21:01:35.862Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 5.635s)
2017-11-18T21:01:35.862Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 8.146s)
2017-11-18T21:01:35.862Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 8.167s)
2017-11-18T21:01:40.274Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 4.649s)
2017-11-18T21:01:50.465Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 17.417s)
2017-11-18T21:02:13.454Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 43.207s)
2017-11-18T21:02:35.695Z - info: [ui] Executing getRemotes: git remote -v (took 22.256s)
2017-11-18T21:02:35.696Z - info: [ui] Executing getRemotes: git remote -v (took 45.253s)
2017-11-18T21:02:35.707Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 22.263s)
2017-11-18T21:02:35.708Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 22.275s)
2017-11-18T21:02:35.708Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 45.252s)
2017-11-18T21:02:35.708Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes -- (took 45.279s)
2017-11-18T21:03:17.820Z - info: [ui] Executing getRemotes: git remote -v (took 6.554s)
2017-11-18T21:13:53.250Z - info: [ui] [AppStore] loading 1 repositories from store
2017-11-18T21:13:53.253Z - info: [ui] [AppStore] found account: stoneddesigner (Oscar D)
2017-11-18T21:13:56.938Z - info: [ui] launching: 0.3.0 (Mac OS 10.12.1)
2017-11-18T21:14:05.133Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 8.264s)
2017-11-18T21:14:34.205Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.426s)

**Comment by mathieudutour** [comment] 2017-11-19 16:54
~930 megabytes 😱 

The first commit will be quite slow because there will be tons of changed files. I'm going to close this issue because it's a duplicate of https://github.com/kactus-io/kactus/issues/66. The workaround is the same (do the first commit "manually"). It should be better after

**Closed by mathieudutour** 2017-11-19 16:54 UTC
