### ISSUE TITLE
How to Regenerate Sketch File from JSON

### ISSUE THREAD

**Issue by hungrysquirrel** [kactus-io/kactus#57] opened 2017-09-13 16:41 UTC
### Description
After checking out a repository I can not see how to Regenerate the Sketch file successfully. 
I click that btn but even after waiting no sketch file appears in my repo directory.

<img width="593" alt="kactus" src="https://user-images.githubusercontent.com/232397/30388820-cc503f76-9865-11e7-9794-886e6b996c4d.png">

### Version
0.2.6

**OS version:** Sierra 10.12.6

### Steps to Reproduce

1. Clone remote repo
1. Click "Regenerate Sketch File from JSON"
1. Can not find or see the regenerated file

**Expected behavior:** Have a regenerated Sketch file from JSON

**Actual behavior:** No file created

**Reproduces how often:** 100%

### Logs
2017-09-12T23:24:10.797Z - info: [ui] Opt out reported.
2017-09-12T23:24:49.895Z - info: [ui] Executing getRemotes: git remote -v (took 3.191s)
2017-09-12T23:24:52.448Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.964s)
2017-09-12T23:25:42.649Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.272s)
2017-09-12T23:26:06.449Z - info: [ui] Executing exportCommit: git archive 6f5fb71c56613a42c6b9001855d74e4966f9354b -o /Users/UserName/Library/Application Support/Kactus/previews/1/6f5fb71c56613a42c6b9001855d74e4966f9354b.tar (took 2.203s)
2017-09-12T23:27:07.981Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 4.969s)
2017-09-12T23:27:08.036Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.372s)
2017-09-12T23:31:59.435Z - info: [ui] Executing exportCommit: git archive 00ea2b6b8e920c37e9bdc2dc86b874902b27b883 -o /Users/UserName/Library/Application Support/Kactus/previews/1/00ea2b6b8e920c37e9bdc2dc86b874902b27b883.tar (took 2.825s)

**Comment by mathieudutour** [comment] 2017-09-14 11:43
That's weird, it should be the other way around. Can you send me the link to your repo so that I can try?

**Comment by hungrysquirrel** [comment] 2017-09-14 13:04
I'm unable to share the repo due to enterprise restrictions. Is there possibly another way to go about this?

Maybe I'll make a test public repo with a similar sketch file and then I can share with you for testing. Would that work for you?

________________________________

**Comment by mathieudutour** [comment] 2017-09-14 13:47
yep perfect, just want to be able to reproduce the bug :)

**Comment by hungrysquirrel** [comment] 2017-09-14 19:56
@mathieudutour My test repo works fine. For some reason in my other repo there is no 
```document.json``` being produced. Could this be the reason why I can not regenerate my Sketch File From JSON?

**Comment by mathieudutour** [comment] 2017-09-14 19:58
oh yes, when there is no document.json, I consider that you can't regenerate the file (which is true). When you export the sketch file, is something showing up in the logs?

**Comment by hungrysquirrel** [comment] 2017-09-14 20:00
@mathieudutour Here's my log

2017-09-14T15:58:22.847Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 4.799s)
2017-09-14T15:59:05.511Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color (took 42.108s)
2017-09-14T15:59:05.545Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 42.128s)
2017-09-14T15:59:05.545Z - info: [ui] Executing getRemotes: git remote -v (took 42.137s)
2017-09-14T16:01:34.142Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 4.997s)
2017-09-14T16:04:38.032Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 1.826s)
2017-09-14T16:04:47.600Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 5.309s)
2017-09-14T16:07:30.635Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 4.995s)
2017-09-14T16:09:59.944Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color (took 1.128s)
2017-09-14T16:09:59.949Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.120s)
2017-09-14T16:09:59.950Z - info: [ui] Executing getRemotes: git remote -v (took 1.126s)
2017-09-14T16:10:09.152Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 1.957s)
2017-09-14T16:10:18.109Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 6.859s)
2017-09-14T16:14:20.971Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 1.250s)
2017-09-14T16:14:30.102Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 6.282s)
2017-09-14T16:17:35.325Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.082s)
2017-09-14T16:18:49.792Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 2.285s)
2017-09-14T16:21:40.108Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.025s)
2017-09-14T16:52:15.938Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 85.658s)
2017-09-14T16:52:16.010Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.006s)
2017-09-14T16:52:22.281Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 6.355s)
2017-09-14T16:52:30.875Z - error: [ui] `git rev-parse HEAD` exited with an unexpected code: 128.
HEAD

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

2017-09-14T16:53:29.572Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 11.347s)
2017-09-14T16:53:32.756Z - info: [ui] Executing createCommit: git commit -F - (took 3.184s)
2017-09-14T16:53:42.368Z - info: [ui] Executing exportCommit: git archive 4f36541526098d3063f898d44490642913525d34 -o /Users/jmrubins/Library/Application Support/Kactus/previews/8/4f36541526098d3063f898d44490642913525d34.tar (took 4.437s)
2017-09-14T16:53:45.386Z - info: [ui] Executing exportCommit: git archive 4f36541526098d3063f898d44490642913525d34 -o /Users/jmrubins/Library/Application Support/Kactus/previews/8/4f36541526098d3063f898d44490642913525d34.tar (took 4.472s)
2017-09-14T16:53:48.216Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 10.347s)
2017-09-14T16:54:14.248Z - info: [ui] Executing exportCommit: git archive 4f36541526098d3063f898d44490642913525d34 -o /Users/jmrubins/Library/Application Support/Kactus/previews/8/4f36541526098d3063f898d44490642913525d34.tar (took 1.050s)
2017-09-14T16:58:21.703Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color (took 110.137s)
2017-09-14T16:58:22.395Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 110.805s)
2017-09-14T16:58:22.396Z - info: [ui] Executing getRemotes: git remote -v (took 110.821s)
2017-09-14T16:58:28.361Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 5.359s)
2017-09-14T16:58:56.154Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 8.714s)
2017-09-14T16:58:56.156Z - info: [ui] Executing getRemotes: git remote -v (took 8.722s)
2017-09-14T16:58:56.157Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color (took 8.733s)
2017-09-14T17:03:55.573Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.756s)
2017-09-14T17:04:29.808Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 3.190s)
2017-09-14T19:54:25.131Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.828s)

**Comment by mathieudutour** [comment] 2017-09-14 20:04
hum it doesn't seem like there is an error 🤔 

if you can send me your sketch file by email or DM, that'd be awesome

**Comment by hungrysquirrel** [comment] 2017-09-14 20:05
ok will do now

**Comment by hungrysquirrel** [comment] 2017-09-14 20:09
Sent

**Comment by hungrysquirrel** [comment] 2017-09-14 20:09
@mathieudutour Sent

**Comment by hungrysquirrel** [comment] 2017-09-14 20:35
@mathieudutour I am testing another approach. I am making a new sketch file by first doing the following:

1. Make new repo
1. Copy all symbols from my sketch file to my new file
1. Copy pages over from my old file into my new file

I do see that there is now a document.json file however I am seeing some bad result....now my symbol overrides are all additive for example in my "clean" file this component looks like this

![devops-ui-kit_sketch](https://user-images.githubusercontent.com/232397/30454446-359a16c8-9951-11e7-82dd-8fa4887416de.png)

And my regenerated file looks like this...more overrides included for this one component that I could have ever imagined...so long the actual overrides I'd expect are all the way at the bottom.
![test_sketch](https://user-images.githubusercontent.com/232397/30454551-911da01e-9951-11e7-9628-a1923e9e547b.png)

**Comment by mathieudutour** [comment] 2017-09-14 21:15
Hum weird. Did you make sure to close the file on sketch before regenerating it?

There is a bug in sketch which kind of breaks everything when refreshing the file.

**Comment by hungrysquirrel** [comment] 2017-09-14 21:28
@mathieudutour 

RE: Symbol overrides issue
I think what happened was I copied over all my symbols and then when I copied over pages using the same symbols I got duplicate symbols!

RE: Regenerating a file from JSON
I am still stumped as to why this will not work with my original file. I was sure to close the Sketch file before regenerating it. How did you fare with your test?

**Comment by mathieudutour** [comment] 2017-09-15 09:45
RE: Symbol overrides issue
Looks like a sketch bug. I'll see if I can talk to them about that.

RE: Regenerating a file from JSON
I created a new repository and added the file you sent me. It worked fine for me.
Let's try to find what happened:

* You confirmed that there is no `document.json` in the folder?
* If you put the copy paste the sketch file in the repo and try to click on "Export Sketch File" in Kactus, nothing change?
* if you create a new repository, put the file inside and "Export Sketch File", is a document.json generated? Is the "regenerate Sketch File" button active?

**Comment by hungrysquirrel** [comment] 2017-09-17 00:30
@mathieudutour 

I created a new repo, put my sketch file inside and after some time of processing the "Export Sketch File" button appeared and became active. I clicked it and watched Kactus make the directory structure. I do not see a document.json file being made.

The regenerate Sketch File button is not active either.


<img width="594" alt="devops-ui-kit" src="https://user-images.githubusercontent.com/232397/30516987-a713d938-9b1d-11e7-8876-7f39ed47e154.png">

<img width="1187" alt="kactus" src="https://user-images.githubusercontent.com/232397/30516992-de678cf4-9b1d-11e7-9bf5-a1129e7a6b23.png">

**Comment by hungrysquirrel** [comment] 2017-09-17 00:55
@mathieudutour I have a feeling file size has something to do with document.json not being made.
I did another test: 

1. Started a new repo
1. Named the file the same as my working file
1. When the new file was made I clicked the regenerate JSON btn
1. A document.json file was made
1. I added my actual working file to the directory and it replaced the fake one
1. The export json file to sketch btn had a spinner in it and all the JSON files were regenerated BUT the document.json file was magically removed and not ever remade by Kactus

**Comment by hungrysquirrel** [comment] 2017-09-17 01:48
@mathieudutour 

I also did another approach. I took my large file copied it and page by page kept deleting and rebuilding JSON to see if it was the file size. Still no luck. No document.json file would ever be created even after I deleted everything in the document.

I will email you a new test file in hopes you see what I am experiencing.

**Comment by mathieudutour** [comment] 2017-09-22 20:33
It should be fixed in the version 0.2.7

**Closed** 2017-09-23 07:55 UTC
Labels: bug

**Comment by hungrysquirrel** [comment] 2017-09-23 16:08
@mathieudutour Thank you. Appears to be fixed with my initial testing. Thank you for fixing so quickly. Was this caused by Sketch versions? https://kactus.io/release-notes/

**Comment by mathieudutour** [comment] 2017-09-23 16:09
no it was because of pages containing images in some cases
