### ISSUE TITLE
App crashes every time I try to solve conflict while merging

### ISSUE THREAD

**Issue by TheoKim1** [kactus-io/kactus#93] opened 2018-03-29 01:58 UTC
## Description
When I click conflicted item to solve conflict, app crashes every time.

## Version

Version: 0.3.3
OS: Mac OS 10.13.3

## Steps to Reproduce
Select conflict item.

### Actual Behavior
App Crashes

## Additional Information
This message is displayed every time.
```
TypeError: Cannot read property 'mediaType' of undefined
    at render (app/src/ui/diff/image-diffs/diff-image.tsx:16:38)
    at p (app/node_modules/react-dom/cjs/react-dom.production.min.js:130:272)
    at beginWork (app/node_modules/react-dom/cjs/react-dom.production.min.js:133:378)
    at a (app/node_modules/react-dom/cjs/react-dom.production.min.js:161:87)
    at e (app/node_modules/react-dom/cjs/react-dom.production.min.js:161:422)
    at f (app/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at w (app/node_modules/react-dom/cjs/react-dom.production.min.js:169:88)
    at D (app/node_modules/react-dom/cjs/react-dom.production.min.js:168:412)
    at k (app/node_modules/react-dom/cjs/react-dom.production.min.js:167:1)
    at g (app/node_modules/react-dom/cjs/react-dom.production.min.js:165:434)
    at Object.enqueueSetState (app/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
```

### Logs

[2018-03-29.kactus.production.log](https://github.com/kactus-io/kactus/files/1858355/2018-03-29.kactus.production.log)

**Comment by mathieudutour** [comment] 2018-03-29 05:49
Hum I can't reproduce. Could you perhaps share your repository?

**Comment by synthresin** [comment] 2018-04-05 08:01
I solved the problem using rebase in terminal, so I afraid that I cannot reproduce this anymore, sorry.
(Issue raiser was my co-walker)

**Comment by mathieudutour** [comment] 2018-04-05 08:03
ok, closing this for now. Let's re-open if we can reproduce

**Closed by mathieudutour** 2018-04-05 08:03 UTC
Labels: more-information-needed
